/**
 * Image delivery to the UI.
 *
 * The UI renders images through `SafeElement.setInnerHTML`, and DOMPurify strips
 * `blob:` URLs from that path while allowing `data:image`. So every image has to
 * become a base64 data URL, which is expensive: encoding is O(bytes) and the
 * resulting string is ~33% larger than the source.
 *
 * The cache is therefore the whole design. `resolveImageUrl` is synchronous
 * because the UI calls it during render and cannot await; it returns only what
 * is already cached. Anything missing is warmed in the background at low
 * concurrency, so a gallery of 200 images paints immediately from cache and
 * fills in progressively instead of blocking on 200 encodes.
 */

import { dbg, dbgSpan } from '../core/debug';
import { abToBase64, abToBase64Async, sniffImageMime } from '../core/util/bytes';
import { sleep } from '../core/util/async';
import { encodeWebpQuality } from '../core/util/image';
import { dropBlobUrl, getBlobUrl, idbGet, idbPut, pinBlobUrls, setBlobUrl } from './stores';

/** Encodes an id to a data URL, reusing the cache. Returns '' when absent. */
export async function ensureBlobUrl(id: string): Promise<string> {
  if (!id) return '';
  const cached = getBlobUrl(id);
  if (cached !== undefined) return cached;
  const span = dbgSpan('image.data_url');
  const rec = await idbGet('images', id);
  if (!rec?.png) {
    span.end({ message: `missing png ${id}`, id, background: true }, 'warn');
    return '';
  }
  const mime = (typeof rec.mime === 'string' && rec.mime) || sniffImageMime(rec.png);
  const b64 = await abToBase64Async(rec.png);
  const url = `data:${mime};base64,${b64}`;
  setBlobUrl(id, url);
  span.end({ message: id, bytes: rec.png.byteLength || 0, mime, url_len: url.length, focus: true });
  return url;
}

/** Cache-only lookup. Safe to call from synchronous UI render paths. */
export function resolveImageUrl(cardOrId: unknown): string {
  const id = typeof cardOrId === 'string' ? cardOrId : (cardOrId as { id?: unknown } | null)?.id;
  if (!id) return '';
  return getBlobUrl(String(id)) || '';
}

/**
 * Stores generated bytes and returns a displayable URL.
 *
 * Re-encodes to WebP first: at quality 0.8 it is typically a third of the PNG
 * size, which shrinks both the stored blob and the data URL the UI must parse.
 * If the browser cannot encode WebP we keep the PNG rather than fail.
 */
export async function publishImage(
  id: string,
  png: ArrayBuffer,
  location: Record<string, unknown> | null = null,
): Promise<string> {
  const span = dbgSpan('image.publish');
  dropBlobUrl(id);
  let bytes: ArrayBuffer = png;
  let mime = sniffImageMime(png);
  try {
    const webp = await encodeWebpQuality(png, 0.8);
    if (webp) {
      bytes = webp;
      mime = 'image/webp';
    }
  } catch (err) {
    dbg('image.webp', { message: String((err as Error)?.message || err), id }, 'warn');
  }
  await idbPut('images', { id, png: bytes, mime, location: location || {} });

  // The encode can stall on a busy main thread. Wait briefly so the common case
  // returns a ready URL, then hand off rather than blocking the job.
  let url = '';
  try {
    const pending = ensureBlobUrl(id);
    url = await Promise.race([pending, sleep(5000).then(() => resolveImageUrl(id) || '')]);
    if (!url) {
      dbg('image.data_url.defer', { message: id, bytes: bytes?.byteLength || 0, mime, focus: true }, 'warn');
      pending.catch((err: unknown) =>
        console.warn('[Inlay Nexus] deferred data URL failed', (err as Error)?.message || err),
      );
    }
  } catch (err) {
    dbg('image.data_url', { message: String((err as Error)?.message || err), id }, 'warn');
    Promise.resolve()
      .then(() => ensureBlobUrl(id))
      .catch(() => {});
  }
  span.end({
    message: id,
    bytes: bytes?.byteLength || 0,
    src_bytes: png?.byteLength || 0,
    mime,
    has_url: Boolean(url),
    has_location: Boolean(location && Object.keys(location).length),
    focus: true,
  });
  return url;
}

// ── background warming ──────────────────────────────────────────────────────

/**
 * Two at a time: enough to hide latency behind the UI's own render work, low
 * enough that warming a large gallery never starves an in-flight generation.
 */
const WARM_CONCURRENCY = 2;

const warmQueued = new Set<string>();
const warmQueue: string[] = [];
let warmActive = 0;
/** Lifetime counters for the current warm wave (reset when the queue drains). */
let warmWaveTotal = 0;
let warmWaveDone = 0;
let warmNotify: (() => void) | null = null;

export interface WarmProgress {
  pending: number;
  active: number;
  done: number;
  total: number;
  pct: number;
  busy: boolean;
}

/** Snapshot of background image-indexing (data-URL encode) progress. */
export function warmProgress(): WarmProgress {
  const pending = warmQueue.length + warmActive;
  const total = Math.max(warmWaveTotal, warmWaveDone + pending);
  const done = Math.min(warmWaveDone, total);
  const pct = total > 0 ? Math.max(0, Math.min(100, Math.round((done / total) * 100))) : 0;
  return { pending, active: warmActive, done, total, pct, busy: pending > 0 };
}

/** UI hooks this to repaint the dual status bars while images index. */
export function onWarmProgress(fn: (() => void) | null): void {
  warmNotify = typeof fn === 'function' ? fn : null;
}

function notifyWarm(): void {
  try {
    warmNotify?.();
  } catch {
    /* UI paint must never break the warm pump */
  }
}

function pumpWarm(): void {
  while (warmActive < WARM_CONCURRENCY && warmQueue.length) {
    const id = warmQueue.shift() as string;
    warmActive += 1;
    notifyWarm();
    ensureBlobUrl(id)
      .catch(() => {})
      .finally(() => {
        warmActive -= 1;
        warmQueued.delete(id);
        warmWaveDone += 1;
        if (warmQueue.length === 0 && warmActive === 0) {
          // Wave finished — allow the next enqueue batch to start a fresh total.
          warmWaveTotal = 0;
          warmWaveDone = 0;
        }
        notifyWarm();
        pumpWarm();
      });
  }
}

export function enqueueWarm(id: unknown): void {
  const key = String(id || '');
  if (!key || getBlobUrl(key) !== undefined || warmQueued.has(key)) return;
  warmQueued.add(key);
  warmQueue.push(key);
  warmWaveTotal += 1;
  notifyWarm();
  pumpWarm();
}

/**
 * Pin sticky-window ids against LRU eviction and pull them to the front of the
 * warm queue so returning to a message is not stuck behind a long gallery encode.
 */
export function pinImageUrls(ids: unknown[] = []): void {
  const list = [...new Set((ids || []).map(String).filter(Boolean))];
  pinBlobUrls(list);
  if (!list.length) return;
  const pinned = new Set(list);
  const prevPending = warmQueue.length;
  const kept: string[] = [];
  for (const id of warmQueue) {
    if (pinned.has(id)) kept.push(id);
    else warmQueued.delete(id);
  }
  warmQueue.length = 0;
  const front: string[] = [];
  for (const id of list) {
    if (getBlobUrl(id) !== undefined) continue;
    if (!warmQueued.has(id)) {
      warmQueued.add(id);
      warmWaveTotal += 1;
    }
    if (!front.includes(id)) front.push(id);
  }
  const rest = kept.filter((id) => !front.includes(id));
  warmQueue.push(...front, ...rest);
  const dropped = prevPending - kept.length;
  if (dropped > 0) {
    warmWaveTotal = Math.max(warmWaveDone + warmQueue.length + warmActive, warmWaveTotal - dropped);
  }
  notifyWarm();
  pumpWarm();
}

/** Warms a batch and returns the URLs that resolved. */
export async function warmImages(ids: unknown[] = [], { concurrency = WARM_CONCURRENCY } = {}): Promise<string[]> {
  const list = [...new Set((ids || []).map(String).filter(Boolean))];
  const limit = Math.max(1, Number(concurrency) || WARM_CONCURRENCY);
  const need = list.filter((id) => getBlobUrl(id) === undefined);
  if (need.length) {
    warmWaveTotal += need.length;
    notifyWarm();
  }
  for (let i = 0; i < need.length; i += limit) {
    const chunk = need.slice(i, i + limit);
    await Promise.all(
      chunk.map((id) =>
        ensureBlobUrl(id)
          .catch(() => '')
          .finally(() => {
            warmWaveDone += 1;
            if (warmQueue.length === 0 && warmActive === 0 && warmWaveDone >= warmWaveTotal) {
              warmWaveTotal = 0;
              warmWaveDone = 0;
            }
            notifyWarm();
          }),
      ),
    );
  }
  if (warmQueue.length === 0 && warmActive === 0) {
    warmWaveTotal = 0;
    warmWaveDone = 0;
    notifyWarm();
  }
  return list.map((id) => resolveImageUrl(id)).filter(Boolean);
}

export interface AttachUrlOptions {
  /** Only these ids are encoded synchronously; the rest use cache + warming. */
  ids?: Iterable<unknown>;
  /** Never encode synchronously. The gallery list default. */
  cachedOnly?: boolean;
}

/**
 * Walks a response payload and fills in `image_url` on anything card-shaped.
 *
 * Mutates in place, matching 1.x: these are freshly built response objects, and
 * copying them would double peak memory for a payload that already carries
 * hundreds of data URLs.
 */
export async function attachImageUrls<T>(obj: T, opts: AttachUrlOptions = {}): Promise<T> {
  if (!obj || typeof obj !== 'object') return obj;
  if (Array.isArray(obj)) {
    for (let i = 0; i < obj.length; i += 1) obj[i] = await attachImageUrls(obj[i], opts);
    return obj;
  }
  const rec = obj as Record<string, unknown>;
  const isCard =
    typeof rec.id === 'string' &&
    (typeof rec.image_url === 'string' || rec.image_path != null || 'shot_index' in rec || 'main_prompt' in rec);
  if (isCard) {
    const id = String(rec.id);
    const filter = opts.ids != null ? new Set([...opts.ids].map(String)) : null;
    const eager = !opts.cachedOnly && (!filter || filter.has(id));
    if (eager) {
      const url = await ensureBlobUrl(id);
      if (url) rec.image_url = url;
    } else {
      rec.image_url = resolveImageUrl(id) || '';
      if (!rec.image_url) enqueueWarm(id);
    }
    return obj;
  }
  for (const key of Object.keys(rec)) {
    if (rec[key] && typeof rec[key] === 'object') {
      rec[key] = await attachImageUrls(rec[key], opts);
    }
  }
  return obj;
}

/** Synchronous data URL for the two singleton preview images held in memory. */
export function pngToDataUrl(png: ArrayBuffer | null | undefined): string {
  if (!png) return '';
  return `data:${sniffImageMime(png)};base64,${abToBase64(png)}`;
}
